### ISSUE TITLE
Easy Distractor Code

### ISSUE THREAD

**Issue by litcoderr** [sejong-rcv/VVS#1]
Hello,

I was wondering if your team can provide an official code that extracts easy distractor.

Thank you.

**Comment by LimGeunTaekk** [comment]
Thank you for your attention to our work!

I've updated the code in the repository, so please check it out here.

[https://github.com/sejong-rcv/VVS/blob/main/easy_distractor_extract.py](https://github.com/sejong-rcv/VVS/blob/main/easy_distractor_extract.py)

![code](https://github.com/sejong-rcv/VVS/assets/70448161/ef6c84a5-40f1-4894-b664-acd1ad99e1e0)

Positioning the videos you want to check and providing the folder path will facilitate the extraction of easy distractors.

~~~~
├── root_dir
   ├── video_1
   ├── video_2
   └── ...
~~~~
    
Feel free to ask if you have any other questions or concerns!

**Comment by LimGeunTaekk** [comment]
@litcoderr

**Comment by litcoderr** [comment]
Thank you for the fast update!
